# docker-compose.yml - DataLive Golden Path Edition
# Everything runs with `docker-compose up -d` - no additional steps required

services:
  # =============================================================================
  # Core Database Services
  # =============================================================================
  
  postgres:
    image: pgvector/pgvector:pg16
    container_name: datalive-postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - datalive-net

  neo4j:
    image: neo4j:2025.01
    container_name: datalive-neo4j
    restart: unless-stopped
    env_file: .env
    environment:
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_server_https_enabled=false
      - NEO4J_server_http_enabled=true
      - NEO4J_server_http_listen__address=0.0.0.0:7474
      - NEO4J_server_config_strict__validation_enabled=false
      # Neo4j 2025.01 optimizations
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4J_server_memory_pagecache_size=512m
      # Block format is default in 2025.01 for new databases
      - NEO4J_db_format=block
      # SSL/TLS hostname verification enabled by default in 2025.01
      - NEO4J_dbms_ssl_policy_bolt_enabled=false
      - NEO4J_dbms_ssl_policy_https_enabled=false
    ports:
      - "7474:7474"   # HTTP
      - "7473:7473"   # HTTPS
      - "7687:7687"   # Bolt
    volumes:
      - neo4j-data:/data
      - ./init-automated-configs/neo4j/ssl:/ssl:ro
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:7474 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 45s
    networks:
      - datalive-net

  qdrant:
    image: qdrant/qdrant:latest
    container_name: datalive-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
    # healthcheck:
    #   test: ["CMD-SHELL", "nc -z localhost 6333 || exit 1"]
    #   interval: 15s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 30s
    networks:
      - datalive-net

  minio:
    image: minio/minio:latest
    container_name: datalive-minio
    restart: unless-stopped
    env_file: .env
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - datalive-net

  redis:
    image: redis:7-alpine
    container_name: datalive-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - datalive-net

  # =============================================================================
  # AI & Processing Services
  # =============================================================================

  ollama:
    image: ollama/ollama:latest
    container_name: datalive-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    # healthcheck:
    #   test: ["CMD-SHELL", "nc -z localhost 11434 || exit 1"]
    #   interval: 30s
    #   timeout: 15s
    #   retries: 5
    #   start_period: 60s
    networks:
      - datalive-net

  # =============================================================================
  # Application Services
  # =============================================================================

  n8n:
    image: n8nio/n8n
    container_name: datalive-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file: .env
    volumes:
      - n8n-data:/home/node/.n8n
      - ./datalive_agent/n8n_workflows:/workflows:ro
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - datalive-net

  datalive_agent:
    build:
      context: ./datalive_agent
      dockerfile: Dockerfile
    container_name: datalive-agent
    restart: unless-stopped
    env_file: .env
    ports:
      - "${DATALIVE_AGENT_PORT:-8058}:8058"
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      qdrant:
        condition: service_started
      minio:
        condition: service_healthy
      n8n:
        condition: service_healthy
      ollama:
        condition: service_started
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8058/health')\""]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    networks:
      - datalive-net

  # =============================================================================
  # Monitoring Services
  # =============================================================================

  prometheus:
    image: prom/prometheus:latest
    container_name: datalive-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./init-automated-configs/prometheus:/etc/prometheus:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - datalive-net

  grafana:
    image: grafana/grafana:latest
    container_name: datalive-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - grafana-data:/var/lib/grafana
      - ./init-automated-configs/grafana:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=redis-datasource
    depends_on:
      prometheus:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - datalive-net

  # =============================================================================
  # Initialization Sidecar Containers
  # =============================================================================

  # PostgreSQL Schema Initialization
  postgres-init:
    image: postgres:16-alpine
    container_name: datalive-postgres-init
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./init-automated-configs/postgres:/scripts:ro
      - ./init-automated-configs/postgres/init.sql:/init/init.sql:ro
    command: /scripts/init.sh
    networks:
      - datalive-net

  # Neo4j Knowledge Graph Setup
  neo4j-init:
    image: alpine:latest
    container_name: datalive-neo4j-init
    depends_on:
      neo4j:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./init-automated-configs/neo4j:/scripts:ro
    command: sh -c "apk add --no-cache curl && /scripts/setup.sh"
    networks:
      - datalive-net

  # Qdrant Vector Collections Setup
  qdrant-init:
    image: alpine:latest
    container_name: datalive-qdrant-init
    depends_on:
      qdrant:
        condition: service_started
    volumes:
      - ./init-automated-configs/qdrant:/scripts:ro
    command: sh -c "apk add --no-cache curl && /scripts/setup.sh"
    networks:
      - datalive-net

  # Ollama Model Download
  ollama-pull:
    image: ollama/ollama:latest
    container_name: datalive-ollama-pull
    depends_on:
      ollama:
        condition: service_started
    env_file: .env
    entrypoint: ["sh", "-c"]
    environment:
      - OLLAMA_HOST=http://ollama:11434
    command: |
      "echo '📥 Downloading optimized MINI models for production...' && \
       echo '⚡ Primary model (optimized): ${LLM_MODEL_PRIMARY:-phi4-mini}' && \
       ollama pull ${LLM_MODEL_PRIMARY:-phi4-mini} && \
       echo '🔄 Fallback model (efficient): ${LLM_MODEL_FALLBACK:-phi3:mini}' && \
       ollama pull ${LLM_MODEL_FALLBACK:-phi3:mini} && \
       echo '🧠 Embedding model: ${OLLAMA_EMBEDDING_MODEL:-nomic-embed-text:v1.5}' && \
       ollama pull ${OLLAMA_EMBEDDING_MODEL:-nomic-embed-text:v1.5} && \
       echo '✅ All MINI models downloaded successfully!' && \
       echo '💾 Memory footprint optimized for production' && \
       echo '📊 Available models:' && \
       ollama list"
    networks:
      - datalive-net

  # N8N Auto-configuration
  n8n-setup:
    image: alpine:latest
    container_name: datalive-n8n-setup
    depends_on:
      n8n:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./init-automated-configs/n8n:/scripts:ro
      - ./datalive_agent/n8n_workflows:/workflows:ro
    command: sh -c "apk add --no-cache curl jq && /scripts/setup.sh"
    networks:
      - datalive-net

  # N8N MCP Server for AI-assisted workflow configuration (DEVELOPMENT ONLY)
  # TODO: Remove this service before production deployment
  n8n-mcp:
    build:
      context: ./init-automated-configs/mcp
      dockerfile: Dockerfile
    container_name: datalive-n8n-mcp
    restart: unless-stopped
    profiles:
      - development  # Only runs in development profile
    networks:
      - datalive-net
    volumes:
      - ./init-automated-configs/mcp:/mcp:ro

  # Final System Health Check & Testing
  healthcheck:
    build:
      context: ./init-automated-configs/healthcheck
      dockerfile: Dockerfile
    container_name: datalive-healthcheck
    depends_on:
      datalive_agent:
        condition: service_healthy
      postgres-init:
        condition: service_completed_successfully
      neo4j-init:
        condition: service_completed_successfully
      qdrant-init:
        condition: service_completed_successfully
      n8n-setup:
        condition: service_completed_successfully
      prometheus:
        condition: service_healthy
      grafana:
        condition: service_healthy
    env_file: .env
    environment:
      - TEST_MODE=${TEST_MODE:-quick}
    volumes:
      - ./init-automated-configs/healthcheck:/scripts:ro
      - /tmp/datalive-test-results:/tmp/datalive-test-results
    # Default runs health verification, but can be overridden for testing
    command: ["./verify.sh"]
    networks:
      - datalive-net

# =============================================================================
# Networks
# =============================================================================

networks:
  datalive-net:
    driver: bridge

# =============================================================================
# Volumes
# =============================================================================

volumes:
  postgres-data:
  neo4j-data:
  qdrant-data:
  redis-data:
  minio-data:
  ollama-data:
  n8n-data:
  prometheus-data:
  grafana-data: