groups:
  - name: datalive_alerts
    rules:
      # DataLive Agent Health
      - alert: DataLiveAgentDown
        expr: up{job="datalive-agent"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "DataLive Agent is down"
          description: "DataLive Agent has been down for more than 1 minute."

      # High Response Time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(query_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High query response time"
          description: "95th percentile response time is {{ $value }}s for 5 minutes."

      # Low Cache Hit Rate
      - alert: LowCacheHitRate
        expr: (rate(cache_hit_total[5m]) / (rate(cache_hit_total[5m]) + rate(cache_miss_total[5m]))) < 0.5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is {{ $value | humanizePercentage }} for 10 minutes."

      # High Error Rate
      - alert: HighErrorRate
        expr: rate(query_total{status="error"}[5m]) / rate(query_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate in queries"
          description: "Error rate is {{ $value | humanizePercentage }} for 5 minutes."

      # Memory Usage
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 85% for 5 minutes."

      # Redis Connection Issues
      - alert: RedisConnectionFailure
        expr: redis_connected_clients == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Redis connection failure"
          description: "No Redis clients connected for 2 minutes."