# Qdrant Configuration
service:
  max_request_size_mb: 32
  max_workers: 0
  enable_cors: true

cluster:
  enabled: false

storage:
  performance:
    max_search_threads: 0
  optimizers:
    deleted_threshold: 0.2
    vacuum_min_vector_number: 1000
    default_segment_number: 0
    max_segment_size_kb: 20000
    memmap_threshold_kb: 0
    indexing_threshold_kb: 20000
    flush_interval_sec: 5
    max_optimization_threads: 1

log_level: INFO